#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
    exec sudo "$0" "$@"
fi

gitea_version="1.24.6"

echo "Running update..."

apt-get update
apt-get upgrade -y

echo ""
echo "Checking dependencies..."

for dep in ca-certificates curl git; do
    if ! command -v $dep &> /dev/null; then
        echo "$pkg needed, installing..."
        apt-get install -y $dep
    fi
    echo "$pkg installed"
done

echo ""

if ! command -v docker &> /dev/null; then
    echo "Docker is not installed, installing..."

    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc

    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
        https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null

    apt-get update
    apt-get install -y \
        docker-ce \
        docker-ce-cli \
        containerd.io \
        docker-buildx-plugin \
        docker-compose-plugin
fi

echo "Enabling and starting docker service.."
systemctl enable --now docker.service

default_db_user="gitea"
default_db_passwd="gitea"
default_db_name="gitea"

read -p "Enter database username (default=gitea): " db_user
if [[ -z $db_user ]]; then
    db_user=$default_db_user
fi

read -p "Enter database password (default=gitea): " db_passwd
if [[ -z $db_passwd ]]; then
    db_passwd=$default_db_passwd
fi

read -p "Enter database name (default=gitea): " db_name
if [[ -z $db_name ]]; then
    db_name=$default_db_name
fi

echo ""
echo "DB Username used: $db_user"
echo "DB Password used: $db_passwd"
echo "DB Name used: $db_name"
echo ""
echo "Gitea version used: $gitea_version"

cat <<EOF > docker-compose.yaml
networks:
  gitea:
    external: false
volumes:
  gitea_data:
    driver: local
  postgres_data:
    driver: local
services:
  server:
    image: docker.gitea.com/gitea:${gitea_version}
    container_name: gitea
    restart: always
    networks:
      - gitea
    volumes:
      - gitea_data:/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: db:5432
      GITEA__database__NAME: ${db_name}
      GITEA__database__USER: ${db_user}
      GITEA__database__PASSWORD: ${db_passwd}
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_passwd}
      POSTGRES_DB: ${db_name}
    networks:
      - gitea
    volumes:
      - postgres_data:/var/lib/postgresql/data
EOF

echo ""
echo "docker-compose.yaml created"

echo "Pulling images..."

docker compose pull

echo "Start the container by running"
echo "docker compose up -d"
