name: Sync repo to Gitea
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set git identity
        run: |
          git config --global user.name "${GIT_NAME}"
          git config --global user.email "${GIT_EMAIL}"
        env:
          GIT_NAME: ${{ vars.GIT_NAME }}
          GIT_EMAIL: ${{ vars.GIT_EMAIL }}
      - name: Push to Gitea
        run: |
          git remote add gitea https://${GIT_NAME}:${GITEA_TOKEN}@gitea-lab.ddns.net/badiwidya/gitea.git
          git push --force gitea main
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
